spring:
  cloud:
    stream:
      bindings:
        input:
          destination: c4c_even_data_topic

      kafka:
        binder:
          brokers:
            - 172.19.22.245:9092
            - 172.19.22.245:9093
            - 172.19.22.245:9094

  data:
    mongodb:
      database: 'kafka-store'
      host: 'localhost'
      port: 27017
      password: 'pAzzw0rd'
      username: 'mongo-admin'
      authentication-database: 'admin'

  kafka:
    bootstrap-servers:
      - 172.19.22.245:9092
      - 172.19.22.245:9093
      - 172.19.22.245:9094

mongodb:
  collection: 'external-user-even'
