spring:
  cloud:
    stream:
      function:
        definition: evenOddProcessor
      bindings:
        evenOddProcessor-in-0:
          destination: c4c_original_data_topic
        evenOddProcessor-out-0:
          destination: c4c_even_data_topic
        evenOddProcessor-out-1:
          destination: c4c_odd_data_topic
      kafka:
        binder:
          brokers:
            - 172.19.22.245:9092
            - 172.19.22.245:9093
            - 172.19.22.245:9094
          auto-create-topics: true

  kafka:
    bootstrap-servers:
      - 172.19.22.245:9092
      - 172.19.22.245:9093
      - 172.19.22.245:9094

  application:
    name: even-odd-streaming

server:
  port: 8181
